ccn/core/urls.py
from django.conf.urls import url

from ccn.core.views import home, fisica, matematica, quimica, bbiologia, lbiologia,\
 contatos, sucesso_usuario, cadastro_usuario

urlpatterns = [
	url(r'^$', home, name='home'),
	url(r'^fisica/$', fisica, name='fisica'),
	url(r'^matematica/$', matematica, name='matematica'),
	url(r'^quimica/$', quimica, name='quimica'),
	url(r'^bbiologia/$', bbiologia, name='bbiologia'),
	url(r'^lbiologia/$', lbiologia, name='lbiologia'),	
	url(r'^contatos/$' , contatos, name='contatos' ),_
	url(r'^cadastro-usuario/$', cadastro_usuario, name='cadastrousuario'),
	url(r'^sucesso-usuario/$', sucesso_usuario, name='usuariosucesso'),
]

ccn/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from ccn.core import urls as core_urls

urlpatterns = [
    # Examples:
    # url(r'^$', 'ccn.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^$', include(core_urls, namespace='core')),
    url(r'^admin/', include(admin.site.urls)),
]

ccn/core/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.



class UserProfile(models.Model):
	user = models.OneToOneField(User)
	telefone = models.CharField(u'Celular', max_length=14, help_text='(99)99999-9999')
	foto = models.ImageField(upload_to="media/profile", blank=True)
	data_cadastro = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return "%s %s" % (self.user.first_name, self.user.last_name)


class noticias(models.Model):
	titulo = models.CharField(u'Noticia', max_length=100)
	descricao = models.TextField(u'Finalidade')
	data_noticia = models.DateField(u'Data')
	horario = models.TimeField(u'Horario')
	imagem = models.ImageField(u'Imagem')
	data_criacao = models.DateTimeField(auto_now_add=True)

ccn/core/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import UserProfile

class UserForm(forms.ModelForm):
	#first_name = forms.CharField(widget=forms.TextInput(attrs={'required': 'required'}))
	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email', 'username', 'password')

class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		exclude = ('user', 'data_cadastro')

ccn/core/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileForm

# Create your views here.
def home(request):
	return render(request, 'index.html')
def fisica(request):
	return render(request, 'core/fisica.html')
def matematica(request):
	return render(request, 'core/matematica.html')
def quimica(request):
	return render(request, 'core/quimica.html')
def bbiologia(request):
	return render(request, 'core/bbiologia.html')
def lbiologia(request):
	return render(request, 'core/lbiologia.html')
def contatos(request):
	return render(request, 'core/contatos.html')
def cadastro_usuario(request):
	if request.method == 'POST':
		user_form = UserForm(request.POST)
		profile_form = UserProfileForm(request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()
			profile = profile_form.save(commit=False)
			profile.user = user

			if 'foto' in request.FILES:
				profile.foto = request.FILES['foto']

			profile.save()
			return redirect('core:usuariosucesso')
		else:
			print(user_form.errors, profile_form.errors)
	else:
		user_form = UserForm()
		profile_form = UserProfileForm()

	return render(request, 'core/cadastro_usuario.html',\
		{'user_form': user_form, 'profile_form': profile_form})
def sucesso_usuario(request):
	return render(request, 'core/sucesso_usuario.html')

ccn/core/templates/cadastro_usuario.html
{% extends "index.html" %}

{% load widget_tweaks %}

{% block titulo %}
Cadastro de usuario | {{ block.super }}
{% endblock titulo %}

{% block row %}
<div class="col-md-8">
	<h1>Faça seu cadastro</h1>
	{% if menssagem %}
		{{ menssagem }}
	{% endif %}
	<form action="" method="post" accept-charset="utf-8" enctype="multipart/data-form">
		{% csrf_token %}
		<div class="form-group">
			<label for="id_first_name">Nome</label>
			{{ user_form.first_name|add_class:"form-control"|attr:"required:required" }} 
		</div>
		<div class="form-group">
			<label for="id_last_name">Sobrenome</label>
			{{ user_form.last_name|add_class:"form-control"|attr:"required:required" }}
		</div>
		<div class="form-group">
			<label for="id_email">Email</label>
			{{ user_form.email|add_class:"form-control"|attr:"required:required" }}
		</div>
		<div class="form-group">
			<label for="id_username">Usuário</label>
			{{ user_form.username|add_class:"form-control" }}
		</div>
		<div class="form-group">
			<label for="id_password">Senha</label>
			{{ user_form.password|add_class:"form-control"|attr:"type:password" }}
		</div>
		<div class="form-group">
			<label for="id_telefone">Telefone</label>
			{{ profile_form.telefone|add_class:"form-control" }}
		</div>
		{% if profile_form.telefone.errors %}
		<div class="form-group">
			<div class="alert alert-warning" role="alert">
				{{ profile_form.telefone.errors }}
			</div>
		</div>
		{% endif %}
		<div class="form-group">
			<label for="exampleInputFile">Foto</label>
			{{ profile_form.foto|add_class:"form-control" }}
		</div>
		<button type="submit" class="btn btn-primary">Cadastrar</button>
	</form>
</div>
{% endblock row %}

ccn/core/templates/core/bbiologia.html
{% load staticfiles %}
<!--www.videosdeti.com.br/vagrant.html-->
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title>{% block titulo %}BBiologia{% endblock titulo %}</title>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}">
  <script type="text/javascript" src="{% static "js/jquery-2.1.4.min.js" %}"></script>
  <script type="text/javascript" src="{% static "js/bootstrap.js" %}"></script>
</head>
<body>
      <h1>Coordenação de Bacharelado em Biologia</a></h1>
    </hgroup>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Sobre o Curso </a></li>
        <li class="active"><a href="#">Dorcentes</a></li>
        <li class="active"><a href="#">Diciplinas</a></li>
        <li class="active"><a href="#">Pesquisas</a></li>
        <li class="active"><a href="{% url 'core:contatos' %}">Contatos</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Pesquisar</button>
      </form>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
   </div><!-- /.container-fluid -->
  </script>
</nav>
<div class="row">
    {% block row %}
    {% endblock row %} 
</div>
<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="..." alt="...">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">Media heading</h4>
    ...
  </div>
</div>
</body>
</html>

ccn/core/templates/core/contatos.html
<!DOCTYPE html>
<html lang="pt-br" dir="ltr">
<head>
<title>contatos.html</title>
<meta http-equiv="Content-Type" content="text/html" charset="UTF-8">
<link rel="stylesheet" href="styles/layout.css" type="text/css">
<!--[if lt IE 9]><script src="scripts/html5shiv.js"></script><![endif]-->
</head>
<body>
<div class="wrapper row1">
  <header id="header" class="clear">
    <hgroup>
      <h1><a href="#">Cordenação de Química</a></h1>
	  <h2><a href="#">UESPI</a></h2>
	  <h3><a href="#">CONTATOS</a></h2>
    </hgroup>
    <nav>
      <ul>
        <li><a href="CordenaçãodeQuimica.html">Voltar</a></li>
       <!-- <li><a href="#">noticias</a></li>
        <li><a href="#">downloads</a></li>
        <li><a href="#">centro</a></li>
        <li class="last"><a href="#">cordenações</a></li>  -->
      </ul>
    </nav>
  </header>
</div>
<!-- content -->
<div class="wrapper row2">
  <div id="container" class="clear">
   <p> <h2>Endereço eletrônico: http: //www../uespi.br/ </h2>
 
       <h2>http://www.coordenacaodequimica@hotmail.com</h2>
       <h2>Fone: (86) 3215-7524, ramal 304</h2>
       <h2>Fax: (86) 3213-7200</h2>
	   
        <div id="content">

</p>
    </div>
    <!-- right column -->
    <aside id="right_column">
      <!-- /nova tabela pronta  -->
    </aside>
    <!-- / content body -->
  </div>
</div>
<!-- Footer -->
<div class="wrapper row3">
  <footer id="footer" class="clear">
  
    <p class="fl_left">Copyright &copy; 2014 - Todos os direitos reservados - <a href="#">UESPI</a></p>
    <p class="fl_right">Desenvolvido por Alfredo Inácio </p> 
  </footer>
</div>
</body>
</html>

ccn/core/templates/core/fisica.html
{% load staticfiles %}
<!--www.videosdeti.com.br/vagrant.html-->
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title>{% block titulo %}Fisica{% endblock titulo %}</title>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}">
  <script type="text/javascript" src="{% static "js/jquery-2.1.4.min.js" %}"></script>
  <script type="text/javascript" src="{% static "js/bootstrap.js" %}"></script>
</head>
<body>
<hgroup>
      <h1>Coordenação de Fisica</a></h1>
    </hgroup>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Sobre o Curso </a></li>
        <li class="active"><a href="#">Dorcentes</a></li>
        <li class="active"><a href="#">Diciplinas</a></li>
        <li class="active"><a href="#">Pesquisas</a></li>
        <li class="active"><a href="{% url 'core:contatos' %}">Contatos</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Pesquisar</button>
      </form>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
   </div><!-- /.container-fluid -->
  </script>
</nav>
<div class="row">
    {% block row %}
    {% endblock row %} 
</div>
<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="..." alt="...">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">Media heading</h4>
    ...
  </div>
</div>
</body>
</html>

ccn/core/templates/core/lbiologia.html
{% load staticfiles %}
<!--www.videosdeti.com.br/vagrant.html-->
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title>{% block titulo %}LBiologia{% endblock titulo %}</title>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}">
  <script type="text/javascript" src="{% static "js/jquery-2.1.4.min.js" %}"></script>
  <script type="text/javascript" src="{% static "js/bootstrap.js" %}"></script>
</head>
<body>
      <h1>Coordenação de Licenciatura em Biologia</a></h1>
    </hgroup>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Sobre o Curso </a></li>
        <li class="active"><a href="#">Dorcentes</a></li>
        <li class="active"><a href="#">Diciplinas</a></li>
        <li class="active"><a href="#">Pesquisas</a></li>
        <li class="active"><a href="{% url 'core:contatos' %}">Contatos</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Pesquisar</button>
      </form>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
   </div><!-- /.container-fluid -->
  </script>
</nav>
<div class="row">
    {% block row %}
    {% endblock row %} 
</div>
<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="..." alt="...">
    </a>
  </div>
  <div class="media-body">
    
    ...
  </div>
</div>
</body>
</html>

ccn/core/templates/core/matematica.html
{% load staticfiles %}
<!--www.videosdeti.com.br/vagrant.html-->
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title>{% block titulo %}Matemática{% endblock titulo %}</title>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}">
  <script type="text/javascript" src="{% static "js/jquery-2.1.4.min.js" %}"></script>
  <script type="text/javascript" src="{% static "js/bootstrap.js" %}"></script>
</head>
<body>
      <h1>Coordenação de Matemática</a></h1>
    </hgroup>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Sobre o Curso </a></li>
        <li class="active"><a href="#">Dorcentes</a></li>
        <li class="active"><a href="#">Diciplinas</a></li>
        <li class="active"><a href="#">Pesquisas</a></li>
        <li class="active"><a href="{% url 'core:contatos' %}">Contatos</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Pesquisar</button>
      </form>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
   </div><!-- /.container-fluid -->
  </script>
</nav>
<div class="row">
    {% block row %}
    {% endblock row %} 
</div>
<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="..." alt="...">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">Media heading</h4>
    ...
  </div>
</div>
</body>
</html>

ccn/core/templates/core/quimica.html
{% load staticfiles %}
<!--www.videosdeti.com.br/vagrant.html-->
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title>{% block titulo %}Quimica{% endblock titulo %}</title>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}">
  <script type="text/javascript" src="{% static "js/jquery-2.1.4.min.js" %}"></script>
  <script type="text/javascript" src="{% static "js/bootstrap.js" %}"></script>
</head>
<body>
      <h1>Coordenação de Quimica</a></h1>
    </hgroup>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Sobre o Curso </a></li>
        <li class="active"><a href="#">Dorcentes</a></li>
        <li class="active"><a href="#">Diciplinas</a></li>
        <li class="active"><a href="#">Pesquisas</a></li>
        <li class="active"><a href="{% url 'core:contatos' %}">Contatos</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Pesquisar</button>
      </form>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
   </div><!-- /.container-fluid -->
  </script>
</nav>
<div class="row">
    {% block row %}
    {% endblock row %} 
</div>
<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="..." alt="...">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">Media heading</h4>
    ...
  </div>
</div>
</body>
</html>

ccn/core/templates/index.html
{% load staticfiles %}
<!--www.videosdeti.com.br/vagrant.html   #359fc9-->
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title>{% block titulo %}CCN{% endblock titulo %}</title>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}">
  <script type="text/javascript" src="{% static "js/jquery-2.1.4.min.js" %}"></script>
  <script type="text/javascript" src="{% static "js/bootstrap.js" %}"></script>
</head>
<body >
    <div class=".carousel-indicators .active">
      
      <h1>CCN</a></h1>
    <h2><a href="http://www.uespi.br/site">UESPI</a></h2>
    </div>  
    <nav class="navbar navbar-default" >
    <div class="container-fluid">
    <!-- Marca e alternância se agrupados para melhor visualização móvel -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="true">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"></a>
    </div>

    <!-- Colete as ligações nav , formulários e outros conteúdos para alternar-->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Sobre </a></li>
        <li class="active"><a href="{% url 'core:contatos' %}">Contatos</a></li>
        <li><a href="{% url 'templates:cadastrousuario' %}">Cadastre-se</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Coordenações <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'core:fisica' %}">Licenciatura em Fisica</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'core:matematica' %}">Licenciatura em Matematica</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'core:quimica' %}">Licenciatura em Quimica</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'core:bbiologia' %}">Bacharelado em Biologia</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'core:lbiologia' %}">Licenciatura em Biologia</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Pesquisar</button>
      </form>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
   </div><!-- /.container-fluid -->
  </script>
</nav>

<div class="centro"  >

    {% block row %}

    <div class="col-sm-5">
    <h3>Noticias</h3>
    </div>
<div class="col-sm-5">
<h3>Eventos</h3>
    </div>
    {% endblock row %} 
</div>
<div class="media" style="background-color:#DDD">
  
  </div>
  
    
  </div>
</div>

</body>
</html>

ccn/core/templates/sucesso_usuario.html
{% extends "base.html" %}

{% block titulo %}
Sucesso usuario | {{ block.super }}
{% endblock titulo %}

{% block row %}
<p>Usuario cadastrado com sucesso.</p>
<p>
	Agora voce esta pronto para criar suas campanhas.
</p>
{% endblock row %}